### ISSUE TITLE
Page Renaming throws NullPointerException

### ISSUE THREAD

**Issue by NMuzaffar** [headwirecom/peregrine-cms#102] opened 2019-06-23 12:17 UTC
**Reproduction**

- open pages tab in admin console
- click 'Info' on any page and rename page
- the resource gets renamed, though an error is thrown

![Screenshot 2019-06-23 at 14 16 27](https://user-images.githubusercontent.com/24642899/59976218-8db22580-95c1-11e9-8aec-50325b8b81d6.png)

![Screenshot 2019-06-23 at 14 18 49](https://user-images.githubusercontent.com/24642899/59976235-d79b0b80-95c1-11e9-9c22-15914842bee3.png)

**Comment by devintuffy** [comment] 2019-06-25 21:25
Root cause is that we are making a call to GET the new resource before the POST to change the name has returned:

![Screen Shot 2019-06-25 at 2 22 24 PM](https://user-images.githubusercontent.com/46942507/60134640-ccc4b000-9754-11e9-8e21-2887428fe8bb.png)

...probably an issue with the promise chain? Will continue to investigate..

**Comment by devintuffy** [comment] 2019-06-25 21:44
This is caused by the renamePage() method of:

apps/admin/components/assetview/template.vue

After the call to $perAdminApp.stateAction('renamePage') on line 167, we immediately make a call to $perAdminApp.stateAction('showPageInfo'), before renamePage has returned.

Will fix.

**Comment by bkheadwire** [comment] 2019-09-25 00:53
This is fixed in the feature/actionrewrite branch.

**Comment by flx-sta** [comment] 2020-01-29 16:38
feature/actionrewrite is merged.

**Closed as completed by flx-sta** 2020-01-29 16:38 UTC
Labels: bug
