### ISSUE TITLE
references show old ones for a split-second

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#767] opened 2021-02-26 07:19 UTC
When switching to "references" tab. changing object and switch to it again you can see the references of the old entry for a split-second.

### Reproduction Steps
- create tenant
- move to `Pages`
- click on ℹ️  for `Articles` page
- switch to referneces tab on the right side
- switch to `Assets/placeholders` 
- select `man.jpg` 
- switch to the references tab
- BOOM; you see them for a sec

**Comment by ehdatheadwire** [comment] 2021-03-13 00:38
@Felix-Puetz is this in review and, if so, has it been completed?

**Comment by reusr1** [comment] 2021-03-13 15:01
we still have a discussion going on in https://github.com/headwirecom/peregrine-cms/pull/768#issuecomment-791476980 - need to come to a conclusion on this if the way this changes the UX is acceptable or not - @ehdatheadwire would love to get the feedback of an editor on this one. - removing the 'close please' label for now

**Comment by ehdatheadwire** [comment] 2021-03-16 22:05
Definitely, @reusr1 -- will take a look.

**Comment by flx-sta** [comment] 2021-03-17 11:23
@ehdatheadwire I merged the current version with the simple animation blocking the view of old references.
We should adress a more proper approach in a new enhancement ticket. You coulc create that if you want :)

**Comment by reusr1** [comment] 2021-03-26 02:22
closing this ticket as the issue is solved in develop for now - we can always create a new ticket in the future

**Closed as completed by reusr1** 2021-03-26 02:22 UTC
Labels: bug
