### ISSUE TITLE
references are not recognized

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#344] opened 2020-03-25 22:28 UTC
![image](https://user-images.githubusercontent.com/50131232/77591453-478f4700-6ef0-11ea-8a94-cd5eb91e780f.png)
![image](https://user-images.githubusercontent.com/50131232/77591468-4f4eeb80-6ef0-11ea-8c51-9699058eb62e.png)

**Comment by reusr1** [comment] 2020-03-26 04:32
@Felix-Puetz was not able to reproduce this issue. Your image seems to be from **themeclean**, you however are in the **abcdefg** tenant - are you looking at the right asset?

**Comment by flx-sta** [comment] 2020-03-26 14:45
![image](https://user-images.githubusercontent.com/50131232/77659754-bdd78c00-6f78-11ea-8932-500aa7ca016b.png)

Definietly a bug @reusr1 

![image](https://user-images.githubusercontent.com/50131232/77659788-c6c85d80-6f78-11ea-80c5-09da970e2d96.png)

**Comment by flx-sta** [comment] 2020-03-29 15:53
@NMuzaffar could you have a look at this? there seems to be an issue with searching for references with the new structure in use

**Comment by NMuzaffar** [comment] 2020-03-29 17:33
@Felix-Puetz When the new website gets created it simply copies another website's content. Hence, the reference value in this image component is from themeclean. There is no such logic to replace image path references in development either (AdminResourceHandler service). The only reference change logic is applied to Felibs files when copied. @reusr1 Shall we add some functionality to AdminResourceHandlerService to replace such /content/.* occurences?

**Comment by reusr1** [comment] 2020-03-30 02:23
@NMuzaffar that's not fully true - try to test with themecleanflex as it has better support for changing the urls for its references (you may want to try on develop as a comparison to see if indeed this still works in the contentrewrite branch)

**Comment by NMuzaffar** [comment] 2020-03-31 09:19
@Felix-Puetz Image references in content get changed, try Themecleanflex. @reusr1 Unfortunately, url changing does not apply to references in components (sample fragments) both for develop and our branch.

**Comment by ehdatheadwire** [comment] 2021-03-11 19:05
@reusr1 and @Felix-Puetz is this still an issue and, if so, is it required for 1.0.0 release? I can't replicate the issue in my local instance. If required for 1.0.0 release, please apply the 1.0.0 Release label and milestone. Thank you!

**Comment by reusr1** [comment] 2021-03-13 22:04
I think closing as this is not relevant anymore

**Closed as completed by reusr1** 2021-03-13 22:04 UTC
Labels: bug, #93, scrubbed
