### ISSUE TITLE
Assets with umlauts in their name don't work

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#231] opened 2019-09-19 07:39 UTC
When you upload an asset that has one or more umlauts in his name you get the following Error in your browser console and the build doesn't get displayed:
Failed to load resource: the server responded with a status of 404 (Not Found)
![Bildschirmfoto 2019-09-19 um 09 20 05](https://user-images.githubusercontent.com/50013766/65223393-66d09600-dac1-11e9-8738-c143df569645.png)

**Comment by reusr1** [comment] 2019-09-19 13:02
@schaefa seems to be a backend issue as the image gets uploaded and processed but the url to request it does not work.

**Comment by schaefa** [comment] 2019-09-20 18:13
Created a fix for it that will force a conversion of the file name if the character encoding is not in UTF-8

**Comment by reusr1** [comment] 2019-09-20 18:33
@FabianHaupt this should be fixed in develop, please check if you have a moment and close the ticket if it's all good for you

**Comment by bkheadwire** [comment] 2019-10-08 21:24
The upload is fixed, but fetching the image with the non-ascii character in the name fails.

**Comment by bkheadwire** [comment] 2019-10-11 20:47
Just confirmed that this is a windows issue - default property:
`file.encoding = Cp1252`

Adding
`-Dfile.encoding="UTF-8"`
to sling startup fixed the problem. Recommend adding this to percli start command.

**Comment by flx-sta** [comment] 2019-11-04 07:13
@reusr1 seems to be working perfectly fine 👍

**Closed as completed** 2019-11-27 09:22 UTC
Labels: bug
