### ISSUE TITLE
asset upload with same name: no feedback

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#277] opened 2019-11-27 09:47 UTC
Currently if you upload an asset with the same name the original one is replaced and the user gets no information.

This could lead to "angry" users and should be improved

Mentioned in #192

**Comment by flx-sta** [comment] 2020-01-30 09:55
bump

**Comment by cmrockwell** [comment] 2020-04-10 16:12
Error handling in general seems to be a problem in Peregrine CMS. 

* Improper JCR permissions fail on the backend and JS blows up in many cases
* Creating an Asset with the same name (this issue)
* Creating a Site with a name already taken will have a similar error on the backend, JS error and broken UI

**Comment by cmrockwell** [comment] 2020-04-15 19:38
Couple of thoughts about the original asset getting replaced when a new one with the same name is uploaded to the same parent.   
1. Possibly the servlet could return 204 and the front-end could notify the user that it was updated.
2. If there was some way to restore trash as discussed in issues/365, then angry users would be much less likely

**Comment by flx-sta** [comment] 2020-04-16 04:46
Still inconvenient. Why not used established error handling like windows ?

“Replace”
“Keep both”

Just make sure the duplicate is checked before upload, not like confluence

**Comment by cmrockwell** [comment] 2020-04-16 15:50
Yep. That's it. Simple and effective upfront validation.

**Comment by reusr1** [comment] 2020-04-21 00:31
@cmrockwell after merging the PR I realized there are some issues when dragging the same file again before reloading the page. Seems there are still some edge cases not handled

example: 
- upload a file
- upload the file second time

however, if I reload the page between the 2 uploads this works

**Comment by cmrockwell** [comment] 2020-04-21 00:53
Ok. Thanks for letting me know. I'll take a look tomorrow.

 
 
  On Mon, Apr 20, 2020 at 8:32 PM, Ruben<notifications@github.com> wrote:   


@cmrockwell after merging the PR I realized there are some issues when dragging the same file again before reloading the page. Seems there are still some edge cases not handled

example:
   
   - upload a file
   - upload the file second time

however, if I reload the page between the 2 uploads this works

**Comment by reusr1** [comment] 2020-11-18 13:49
looks like this has been fixed - not able to reproduce, closing the issue

**Closed as completed by reusr1** 2020-11-18 13:49 UTC
Labels: feature, UX/UI, LFA
