### ISSUE TITLE
Refresh does not redirect to login page (valid URL will not work in incognito browser)

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#721] opened 2021-01-29 11:23 UTC
Every day in the morning, when I wake my laptop and refresh the last Peregrine console that I had open the day before - I get a blank page. I got logged out in the session and the URL in the browser does not trigger a redirect to login page.

The simplest case is this though: try to open a valid Peregrine console URL in a fresh incognito window of your browser. Try e.g. [/content/admin/pages/pages.html](http://localhost:8080/content/admin/pages/pages.html). The result is a blank page, not a redirect to login page.

Caveat: does not apply to [/admin/pages/pages.html](http://localhost:8080/admin/pages/pages.html), but somehow one would always get into `/content/admin/` URLs instead of `/admin/`, simple case:
1. Open [localhost:8080](http://localhost:8080),
2. Log in (we're in `/admin/` namespace for now),
3. Assuming you have a tenant - click it.

And voilla - we're in `/content/admin/` space now.

**Comment by ehdatheadwire** [comment] 2021-03-05 21:51
I'd consider this an enhancement, not a bug, @reggie7 -- as in, not sure the use case to fix this is prevalent enough to prioritize it over other bugs/fixes in the queue. 

I'll close/move it for now, but we can always pull it back in/reopen it if you think it needs to be. Thx.

---
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/33

**Closed as completed by ehdatheadwire** 2021-03-05 21:51 UTC
Labels: bug, UX/UI, low, enhancement, proposal

**Comment by reggie7** [comment] 2021-03-08 09:50
@ehdatheadwire yes, I don't think it's prioritized above other bugs. It's an enhancement on one hand, but personally I'd still call this a bug though. Not a highly prioritized, but a sophisticated bug (all other web apps simply in similar scenarios). Thus the labels `bug` + `enhancement` + `low` 😅
