### ISSUE TITLE
Pathbrowser moving into folder and back out -> Vue.warn

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#288] opened 2020-01-24 21:10 UTC
When using the pathbrowser and you navigate around a bit
e.g (keep an eye on js-console while doing);
- You start in themeclean
- navigate back to root
- into example
- back to root -> themeclean

<img width="638" alt="Screenshot 2020-01-24 at 22 07 57" src="https://user-images.githubusercontent.com/50131232/73104148-02519780-3ef6-11ea-8f08-294e801aa4e0.png">

---------

_on develop & develop-sling11_

**Comment by reusr1** [comment] 2020-04-03 05:29
@Felix-Puetz I am not able to reproduce this issue anymore in issues/93 branch. If you can't reproduce it either I think we should close the issue

**Closed as completed** 2020-04-03 05:52 UTC
Labels: feature, LFA
