### ISSUE TITLE
Cant drop new Components between end and start placeholder of two container components

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#115] opened 2019-07-04 13:57 UTC
When you add two container components to your page and you try to drop something between them it doesn't work. It either drops the component in the first or the second container.

**Comment by reusr1** [comment] 2019-07-15 19:35
@bkheadwire please review https://github.com/headwirecom/peregrine-cms/pull/144 and merge/close if the issue is solved

**Comment by bkheadwire** [comment] 2019-07-15 21:13
Confirmed issue solved, PR merged.

**Closed as completed by bkheadwire** 2019-07-15 21:13 UTC
Labels: bug, fixed
